language: python
sudo: required
dist: trusty
env:
  global:
    -JYTHON=false
before_install:
  - if [ "$JYTHON" == "true" ]; then
        hg clone http://hg.python.org/jython;
        cd jython;
        ant;
        cd ..;
        chmod +x "$(pwd)/jython/dist/bin/jython";
        export INTERPRETER="$(pwd)/jython/dist/bin/jython";
        alias jython="$(pwd)/jython/dist/bin/jython";
        export PATH="$(pwd)/jython/dist/bin:$PATH";
        wget --no-verbose https://bootstrap.pypa.io/3.2/get-pip.py;
        $INTERPRETER get-pip.py;
    else
        export INTERPRETER=python;
    fi
  - sudo useradd test -m -s /bin/bash
  - (echo 'test'; echo 'test') | sudo passwd test
  - sudo -E su test -c "echo $'export PS1=\'\u@travis \W \$ \'' >> /home/test/.bashrc"
  - sudo useradd -m testkey -s /bin/bash
  - sudo -E su testkey -c "echo $'export PS1=\'\u@travis \W \$ \'' >> /home/testkey/.bashrc"
  - sudo -E su testkey -c "mkdir -p /home/testkey/.ssh"
  - sudo -E su testkey -c "ssh-keygen -f /home/testkey/.ssh/id_rsa -t rsa -N ''"
  - sudo -E su testkey -c "cp /home/testkey/.ssh/id_rsa.pub /home/testkey/.ssh/authorized_keys"
  - sudo -E su testkey -c "chmod 644 /home/testkey/.ssh/id_rsa"
  - cp /home/testkey/.ssh/id_rsa atest/testdata/keyfiles/
install:
  - pip install -r requirements.txt
matrix:
  include:
    - python: "2.7"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=2.4.1
    - python: "2.7"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=2.3.2
    - python: "2.7"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=2.1.5
    - python: "2.7"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=1.18.5
    - python: "2.7"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=1.16.3
    - python: "2.7"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=1.15.0
    - python: "2.7"
      env:
        - JYTHON=true
        - ROBOTFRAMEWORK=3.0.2
    - python: "3.4"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=2.4.1
    - python: "3.4"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=1.15.0
    - python: "3.5"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=2.4.1

    - python: "3.5"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=1.15.0

    - python: "3.6"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=2.4.1
    - python: "3.6"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=2.2.3
    - python: "3.6"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=2.0.8
    - python: "3.6"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=1.17.6
    - python: "3.6"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - PARAMIKO=1.15.0
before_script:
  - pip install robotframework==$ROBOTFRAMEWORK
  - if [ "$JYTHON" == "true" ]; then
        export CLASSPATH=$CLASSPATH:$TRAVIS_BUILD_DIR/lib/*;
    else
        pip install paramiko==$PARAMIKO;
    fi
script:
  - $INTERPRETER atest/run.py atest