language: python
sudo: required
dist: xenial
env:
  global:
    -JYTHON=false
before_install:
  - if [ "$JYTHON" == "true" ]; then
        wget -O jython.jar http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.1/jython-installer-2.7.1.jar;
        java -jar jython.jar -s -d ~/jython;
        export PATH="~/jython/bin:$PATH";
        export INTERPRETER=jython;
    else
        export INTERPRETER=python;
    fi
  - sudo useradd test -m -s /bin/bash -G travis
  - (echo 'test'; echo 'test') | sudo passwd test
  - sudo -E su test -c "echo $'export PS1=\'\u@travis \W \$ \'' >> /home/test/.bashrc"
  - sudo sh -c "echo 'test   ALL=(ALL:ALL) PASSWD:ALL' > /etc/sudoers.d/passworded"
  - sudo useradd -m testkey -s /bin/bash
  - sudo -E su testkey -c "echo $'export PS1=\'\u@travis \W \$ \'' >> /home/testkey/.bashrc"
  - sudo -E su testkey -c "mkdir -p /home/testkey/.ssh"
  - sudo -E su testkey -c "ssh-keygen -f /home/testkey/.ssh/id_rsa -t rsa -N ''"
  - sudo -E su testkey -c "cp /home/testkey/.ssh/id_rsa.pub /home/testkey/.ssh/authorized_keys"
  - sudo -E su testkey -c "chmod 644 /home/testkey/.ssh/id_rsa"
  - cp /home/testkey/.ssh/id_rsa atest/testdata/keyfiles/
  - sudo bash -c "echo 'Testing pre-login banner' > /etc/ssh/sshd-banner"
  - sudo bash -c "echo 'Banner /etc/ssh/sshd-banner' >> /etc/ssh/sshd_config"
  - sudo bash -c "echo 'Subsystem subsys echo \"Subsystem invoked.\"' >> /etc/ssh/sshd_config"
  - sudo service ssh restart
  - echo $'Host test_hostname\n    Hostname localhost\n' >> ~/.ssh/config
  - eval "$(ssh-agent -s)"
  - ssh-add /home/testkey/.ssh/id_rsa
install:
  - pip install -r requirements-dev.txt docutils
matrix:
  include:
    - python: "3.7"
      env:
        - ROBOTFRAMEWORK=3.1.2
        - PARAMIKO=2.6.0
    - python: "2.7"
      env:
        - ROBOTFRAMEWORK=3.1.2
        - PARAMIKO=2.4.1
    - python: "2.7"
      env:
        - JYTHON=true
        - ROBOTFRAMEWORK=3.1.2
    - python: "3.4"
      env:
        - ROBOTFRAMEWORK=3.1.2
        - PARAMIKO=2.1.5
    - python: "3.5"
      env:
        - ROBOTFRAMEWORK=3.1.2
        - PARAMIKO=1.18.5
    - python: "3.6"
      env:
        - ROBOTFRAMEWORK=3.1.2
        - PARAMIKO=1.15.3
before_script:
  - pip install robotframework==$ROBOTFRAMEWORK
  - if [ "$JYTHON" == "true" ]; then
        export CLASSPATH=$CLASSPATH:$TRAVIS_BUILD_DIR/lib/*;
    else
        pip install paramiko==$PARAMIKO scp;
    fi
script:
  - $INTERPRETER atest/run.py atest
